apiVersion: v1
kind: Service
metadata:
  name: activemq
  namespace: activemq
  labels:
    app: activemq
spec:
  selector:
    app: activemq
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP
#  externalTrafficPolicy: Local
  type: LoadBalancer
  externalIPs:
  - 192.168.35.237